### PR TITLE
Update modsecurity

### PR DESCRIPTION
**Pull request by GMartinez-Sisti**
- Update modsecurity to [2.9.5](https://github.com/SpiderLabs/ModSecurity/releases/tag/v2.9.5)
- Fix local tests

### CODE REVIEW

**Comment by jcmoraisjr** [comment]
Your branch is broken for me with the following error message:

```
config.status: executing libtool commands
make: Entering directory '/usr/src/modsecurity/standalone'
make: ../build/install-sh: Operation not permitted
make: *** [Makefile:659: ../apache2/.dirstamp] Error 127
make: Leaving directory '/usr/src/modsecurity/standalone'
```

The interesting part is that master is broken as well, with another message:

```
config.status: creating apache2/modsecurity_config_auto.h
config.status: executing depfiles commands
config.status: error: in `/usr/src/modsecurity':
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  Try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
See `config.log' for more details
```

I'm building on a virtual flatcar box. Just created a new clean vm just to confirm, same problem. I'll give another try in the weekend, or maybe you have an idea what's happening here.

**Comment by GMartinez-Sisti** [comment]
Hi, there is an issue with the test script on the main branch that I fixed on this branch (`./run.sh: line 27: ci_log_entry: command not found`) but other than that both work.

Are you building it inside docker?

**Comment by jcmoraisjr** [comment]
Fixed when I move to `alpine:3.13`. What if you `docker pull alpine:3.14` in order to use an up to date version?

**Comment by GMartinez-Sisti** [comment]
I'm not sure what you mean. The repo already uses alpine:3.14 for both the containers:

- https://github.com/jcmoraisjr/modsecurity-spoa/blob/master/rootfs/Dockerfile#L1
- https://github.com/jcmoraisjr/modsecurity-spoa/blob/master/test/Dockerfile#L1

**Comment by jcmoraisjr** [comment]
I mean you update your local copy. This worked in the past with 3.14 and actually work with 3.13, but it's breaking with an up to date 3.14 image.

**Comment by GMartinez-Sisti** [comment]
Got it now. Tried to pull the latest but already had it:
```sh
→ docker pull alpine:3.14
3.14: Pulling from library/alpine
Digest: sha256:635f0aa53d99017b38d1a0aa5b2082f7812b03e3cdb299103fe77b5c8a07f1d2
Status: Image is up to date for alpine:3.14
docker.io/library/alpine:3.14
```

Are you using amd64?
```sh
→ docker version
Client:
 Cloud integration: v1.0.20
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:43:15 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:30 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by GMartinez-Sisti** [comment]
Can you try with `alpine:3.15`? If it works these two can be merged before this to fix the issue:
- https://github.com/jcmoraisjr/modsecurity-spoa/pull/13
- https://github.com/jcmoraisjr/modsecurity-spoa/pull/14

**Comment by jcmoraisjr** [comment]
Finally took the time to try a few distinct approaches and what solved the issue was updating the OS where docker daemon is running. Same OS (Flatcar), kernel changed from 5.4 to 5.10. ¯\_(ツ)_/¯

Let's merge this change and tag a new version, we're a bit late. I'll prefer to update the base image in a new release so people have an option if something does wrong with the new one. Btw thank you so much for help us to maintain this image up to date.

**Pull request merged**
